spring:
  data:
    mongodb:
      host: 10.30.4.3
      port: 27017
      database: test
  datasource:
    url: jdbc:mysql://10.30.10.235:3306/study?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
  port: 8090

logging:
  path: /log
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    level:
      com.example.demo=DEBUG
      org.springframework.web=DEBUG
      org.hibernate=ERROR
      root=WARN
